### ISSUE TITLE
CT Sanity check for level icon layout

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-fraction#13]
```
build-a-fraction : xss-fuzz
http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/build-a-fraction/build-a-fraction_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1683626850194%22%2C%22timestamp%22%3A1683628848121%7D&brand=phet&ea&fuzz&stringTest=xss
Query: brand=phet&ea&fuzz&stringTest=xss
Uncaught Error: Assertion failed: Sanity check for level icon layout
Error: Assertion failed: Sanity check for level icon layout
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/assert/js/assert.js:28:13)
at assert (BuildingGameScreenView.js:523:14)
at createLevelIcon (BuildingGameScreenView.js:96:82)
at Array.map
at map (BuildingGameScreenView.js:96:45)
at (BuildAFractionScreen.js:21:15)
at createView (Screen.ts:308:22)
at initializeView (Sim.ts:886:15)
at (Sim.ts:894:25)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:07:30 AM

----------------------------------

build-a-fraction : xss-fuzz
http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/build-a-fraction/build-a-fraction_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1683626850194%22%2C%22timestamp%22%3A1683632787121%7D&brand=phet&ea&fuzz&stringTest=xss
Query: brand=phet&ea&fuzz&stringTest=xss
Uncaught Error: Assertion failed: Sanity check for level icon layout
Error: Assertion failed: Sanity check for level icon layout
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/assert/js/assert.js:28:13)
at assert (BuildingGameScreenView.js:523:14)
at createLevelIcon (BuildingGameScreenView.js:96:82)
at Array.map
at map (BuildingGameScreenView.js:96:45)
at (BuildAFractionScreen.js:21:15)
at createView (Screen.ts:308:22)
at initializeView (Sim.ts:886:15)
at (Sim.ts:894:25)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:07:30 AM

----------------------------------

build-a-fraction : xss-fuzz
http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/build-a-fraction/build-a-fraction_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1683626850194%22%2C%22timestamp%22%3A1683634359822%7D&brand=phet&ea&fuzz&stringTest=xss
Query: brand=phet&ea&fuzz&stringTest=xss
Uncaught Error: Assertion failed: Sanity check for level icon layout
Error: Assertion failed: Sanity check for level icon layout
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/assert/js/assert.js:28:13)
at assert (BuildingGameScreenView.js:523:14)
at createLevelIcon (BuildingGameScreenView.js:96:82)
at Array.map
at map (BuildingGameScreenView.js:96:45)
at (BuildAFractionScreen.js:21:15)
at createView (Screen.ts:308:22)
at initializeView (Sim.ts:886:15)
at (Sim.ts:894:25)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:07:30 AM

----------------------------------

build-a-fraction : xss-fuzz
http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/build-a-fraction/build-a-fraction_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1683626850194%22%2C%22timestamp%22%3A1683636816855%7D&brand=phet&ea&fuzz&stringTest=xss
Query: brand=phet&ea&fuzz&stringTest=xss
Uncaught Error: Assertion failed: Sanity check for level icon layout
Error: Assertion failed: Sanity check for level icon layout
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/assert/js/assert.js:28:13)
at assert (BuildingGameScreenView.js:523:14)
at createLevelIcon (BuildingGameScreenView.js:96:82)
at Array.map
at map (BuildingGameScreenView.js:96:45)
at (BuildAFractionScreen.js:21:15)
at createView (Screen.ts:308:22)
at initializeView (Sim.ts:886:15)
at (Sim.ts:894:25)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:07:30 AM

----------------------------------

build-a-fraction : xss-fuzz
http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/build-a-fraction/build-a-fraction_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1683626850194%22%2C%22timestamp%22%3A1683638921615%7D&brand=phet&ea&fuzz&stringTest=xss
Query: brand=phet&ea&fuzz&stringTest=xss
Uncaught Error: Assertion failed: Sanity check for level icon layout
Error: Assertion failed: Sanity check for level icon layout
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/assert/js/assert.js:28:13)
at assert (BuildingGameScreenView.js:523:14)
at createLevelIcon (BuildingGameScreenView.js:96:82)
at Array.map
at map (BuildingGameScreenView.js:96:45)
at (BuildAFractionScreen.js:21:15)
at createView (Screen.ts:308:22)
at initializeView (Sim.ts:886:15)
at (Sim.ts:894:25)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:07:30 AM

----------------------------------

build-a-fraction : xss-fuzz
http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/build-a-fraction/build-a-fraction_en.html?continuousTest=%7B%22test%22%3A%5B%22build-a-fraction%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1683626850194%22%2C%22timestamp%22%3A1683641135024%7D&brand=phet&ea&fuzz&stringTest=xss
Query: brand=phet&ea&fuzz&stringTest=xss
Uncaught Error: Assertion failed: Sanity check for level icon layout
Error: Assertion failed: Sanity check for level icon layout
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683626850194/assert/js/assert.js:28:13)
at assert (BuildingGameScreenView.js:523:14)
at createLevelIcon (BuildingGameScreenView.js:96:82)
at Array.map
at map (BuildingGameScreenView.js:96:45)
at (BuildAFractionScreen.js:21:15)
at createView (Screen.ts:308:22)
at initializeView (Sim.ts:886:15)
at (Sim.ts:894:25)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:07:30 AM
```

**Comment by samreid** [comment]
May be a rounding error? After the above assertion message improvement, we got:

```
Query: brand=phet&ea&fuzz&stringTest=xss
Uncaught Error: Assertion failed: Sanity check for level icon layout: - BuildingGame:label.bounds
[x:(0,90),y:(0,129)]
[x:(0,90.00000000000001),y:(0,0.723307355172031)]
Error: Assertion failed: Sanity check for level icon layout: - BuildingGame:label.bounds
```
